implemented all method
mate-academy/jv-jdbc-intro pull request #342
Opened 2024-05-03 09:41 UTC by vladshender

2024-05-03 10:26 UTC, kerrrusha requested changes

2024-05-03 10:26 UTC, kerrrusha commented on src/main/java/mate/academy/DatabaseInitializer.java
> +
```suggestion
```

2024-05-03 10:26 UTC, kerrrusha commented on src/main/java/mate/academy/DatabaseInitializer.java
> +                    new FileReader("src/main/resources/init_db.sql"))) {
should be constant

2024-05-03 10:26 UTC, kerrrusha commented on src/main/java/mate/academy/DatabaseInitializer.java
> +    }
separate this method on two methods - IO reading file and execution of sql statements

2024-05-03 10:26 UTC, kerrrusha commented on src/main/resources/init_db.sql
> +CREATE TABLE `books` (`id` BIGINT NOT NULL AUTO_INCREMENT, `title` VARCHAR(255), `price` INT, PRIMARY KEY (`id`));
```suggestion
CREATE TABLE `books` (
`id` BIGINT NOT NULL AUTO_INCREMENT, 
`title` VARCHAR(255), 
`price` INT, 
PRIMARY KEY (`id`)
);

```

2024-05-03 20:20 UTC, sarakhmen requested changes
Let's slightly improve your solution one more time :)

2024-05-03 20:20 UTC, sarakhmen commented on src/main/java/mate/academy/DatabaseInitializer.java
> +            String sqlCommands = parseCommandFile(FILE_PATH);
you shouldn't parse the file while the connection is opened. I'd recommend calling two methods inside your createTable: the first one to parse file and the second one to execute queries

2024-05-04 11:11 UTC, okuzan approved these changes

2024-05-04 11:11 UTC, okuzan commented on src/main/resources/init_db.sql
> +);
always review your PR and add an empty line at the end of each file
![image](https://github.com/mate-academy/jv-jdbc-intro/assets/49767049/b5cf7470-6b4b-48f5-827e-da08a2af0b2b)

2026-03-08 07:28 UTC, closed without merging