Created Book entity and BookDao repository interface, and it's implem…
mate-academy/jv-jdbc-intro pull request #44
Opened 2023-08-09 13:39 UTC by OlegStashkiv

…entation.

2023-08-09 15:04 UTC, holsoni requested changes
Just add empty lines at the end of files

2023-08-09 15:04 UTC, holsoni commented on pom.xml
>  </project>
Add empty line in the end of file

2023-08-09 17:03 UTC, holsoni approved these changes

2023-08-10 07:21 UTC, nacenik requested changes
Good solution) let's improve it)

2023-08-10 07:21 UTC, nacenik commented on src/main/java/mate/academy/dao/BookDao.java
> +    boolean deleteById(Long id);
don't forget to put spaces between methods 
```suggestion
    Book create(Book book);
    
    Optional<Book> findById(Long id);
    
    List<Book> findAll();
    
    Book update(Book book);
    
    boolean deleteById(Long id);
```

2023-08-10 07:21 UTC, nacenik commented on src/main/java/mate/academy/ConnectionUtil.java
> +public class ConnectionUtil {
better put this class in separate package `util`

2023-08-10 07:21 UTC, nacenik commented on src/main/java/mate/academy/dao/implementation/BookDaoImpl.java
> +                        + " but inserted 0 rows");
What row is expected to insert?

2023-08-10 07:21 UTC, nacenik commented on src/main/java/mate/academy/dao/implementation/BookDaoImpl.java
> +                        + " but inserted 0 rows");
insert or update?

2023-08-11 09:51 UTC, Vasul-Pankiv approved these changes

2026-05-21 07:59 UTC, closed without merging