implement BookDao interface
mate-academy/jv-jdbc-intro pull request #451
Opened 2024-11-15 23:01 UTC by skotsurskiy

2024-11-15 23:03 UTC, mateacademy-ai-mentor requested changes
Thank you for your hard work on this project! 😊 There are a few critical issues that need to be addressed before we can move forward. The `Book` model's `price` field should be of type `BigDecimal` instead of `int`, which is essential for handling monetary values accurately. Additionally, the `deleteById` method should return a boolean based on the result of `executeUpdate()`, ensuring it accurately reflects the operation's success. Lastly, the missing `init_db.sql` file is crucial for setting up the database schema. Once these issues are resolved, your code will be in great shape! Keep up the great work! 🚀

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

🔄 Fix the issues, commit the changes, and then re-request my review using the `Re-request review` button in the Reviewers tab.

2024-11-16 19:30 UTC, mateacademy-ai-mentor approved these changes
****

Your Pull Request has been approved! 🎉

Great job on implementing the `BookDao` operations and setting up the database connection. However, there are a few critical issues that need to be addressed to ensure the code functions correctly and adheres to best practices:

1. **Book Model Price Field**: The `price` field in the `Book` model should be of type `BigDecimal` instead of `int` to accurately handle monetary values. This change is crucial for precision in financial calculations.

2. **SQL Handling**: Ensure that SQL keywords are in uppercase for readability, and store each SQL query in a separate variable before using it in a `PreparedStatement`.

3. **Database Initialization**: The `init_db.sql` file is missing. This file is necessary for setting up the database schema and should be included in the `src/main/resources` folder.

4. **Method Updates**: Update the `setPrice` method to accept a `BigDecimal` parameter, and change the return type of `getPrice` to `BigDecimal`. Also, ensure that `setInt` and `getObject` methods are correctly handling `BigDecimal` for the `price` field.

5. **Equality and Hashing**: Update the `toString`, `hashCode`, and equality checks to handle `BigDecimal` for the `price` field accurately.

These changes are important for the functionality and maintainability of your code. Please address these issues in your next iteration. Keep up the good work, and continue learning from these improvements! 🚀

✨ Please rate this review in the Platform's notification center. I will be grateful for your feedback! ✨

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/Main.java
> +        firstBook.setPrice(50);
The `setPrice` method is currently using an `int` value. Ensure that the `Book` model's `price` field is of type `BigDecimal` and update this line to use `BigDecimal.valueOf(50)` instead.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/Main.java
> +        secondBook.setPrice(70);
The `setPrice` method is currently using an `int` value. Ensure that the `Book` model's `price` field is of type `BigDecimal` and update this line to use `BigDecimal.valueOf(70)` instead.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/Main.java
> +        thirdBook.setPrice(35);
The `setPrice` method is currently using an `int` value. Ensure that the `Book` model's `price` field is of type `BigDecimal` and update this line to use `BigDecimal.valueOf(35)` instead.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/Main.java
> +        updateBook.setPrice(100);
The `setPrice` method is currently using an `int` value. Ensure that the `Book` model's `price` field is of type `BigDecimal` and update this line to use `BigDecimal.valueOf(100)` instead.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            statement.setInt(2, book.getPrice());
The `setInt` method is used for setting the `price`. Change this to `setBigDecimal` and ensure the `price` is of type `BigDecimal`.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +                book.setPrice(resultSet.getObject("price", Integer.class));
The `getObject` method is used to retrieve the `price` as an `Integer`. Change this to retrieve it as a `BigDecimal`.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +                book.setPrice(resultSet.getObject("price", Integer.class));
The `getObject` method is used to retrieve the `price` as an `Integer`. Change this to retrieve it as a `BigDecimal`.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            statement.setInt(2, book.getPrice());
The `setInt` method is used for setting the `price`. Change this to `setBigDecimal` and ensure the `price` is of type `BigDecimal`.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/model/Book.java
> +    private int price;
The `price` field should be of type `BigDecimal` instead of `int` to handle monetary values accurately.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/model/Book.java
> +    public int getPrice() {
Change the return type of `getPrice` to `BigDecimal`.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/model/Book.java
> +    public void setPrice(int price) {
Change the parameter type of `setPrice` to `BigDecimal`.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/model/Book.java
> +        return price == book.price
Update the equality check for `price` to use `BigDecimal.compareTo()` for accurate comparison.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/model/Book.java
> +        return Objects.hash(id, title, price);
Update the `hashCode` method to handle `BigDecimal` for the `price` field.

2024-11-16 19:30 UTC, mateacademy-ai-mentor commented on src/main/java/mate/academy/model/Book.java
> +        return "Book{" + "id=" + id + ", title='" + title + '\'' + ", price=" + price + '}';
Update the `toString` method to handle `BigDecimal` for the `price` field.

2024-11-17 16:36 UTC, Elena-Bruyako requested changes

2024-11-17 16:36 UTC, Elena-Bruyako commented on src/main/java/mate/academy/Main.java
>      public static void main(String[] args) {
```suggestion
    public static void main(String[] args) {
        BookDao bookDao = (BookDao) injector.getInstance(BookDao.class);
```

2024-11-17 16:36 UTC, Elena-Bruyako commented on src/main/java/mate/academy/Main.java
> +    public static final BookDao bookDao = (BookDao) injector.getInstance(BookDao.class);
```suggestion
```

2024-11-17 16:36 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dao/BookDao.java
> +@Dao
```suggestion
```

2024-11-17 16:36 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +                Book book = new Book();
create separate method to map resultSet to book

2024-11-17 16:36 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +                Book book = new Book();
use method from method above

2024-11-17 16:36 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            }
```suggestion
```

2024-11-17 16:36 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            return rowsAffected >= 1;
```suggestion
            return statement.executeUpdate() > 0;
```

2024-11-18 09:20 UTC, liliia-ponomarenko approved these changes
good job! 👍

2025-09-27 08:01 UTC, closed without merging