Create bookDaoImpl
mate-academy/jv-jdbc-intro pull request #59
Opened 2023-08-11 13:38 UTC by ConfusedSatlan

2023-08-13 06:40 UTC, OleksandrSaven approved these changes

2023-08-13 06:40 UTC, OleksandrSaven commented on src/main/resources/init_db.sql
> +);
Add empty line

2023-08-13 06:40 UTC, OleksandrSaven commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +    private static final int SECOND_INDEX = 2;
the name of the variable should be informative

2023-08-14 13:09 UTC, vovasalyha requested changes

2023-08-14 13:09 UTC, vovasalyha commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +                String title = resultSet.getString(TITLE_NAME);
Do not duplicate the code. Extract mapping logic in separate private method which accepts ResultSet and use it in `finaAll()` too.

2023-08-14 13:09 UTC, vovasalyha commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            if (affectedRows < ROW_EXIST_NUM) {
It's okay if zero rows are affected, do not throw an Exception.

2023-08-14 13:09 UTC, vovasalyha commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            if (affectedRows < ROW_EXIST_NUM) {
It's okay if zero rows are affected, do not throw an Exception. You return boolean value indicating whether 0 or more rows were affected.

2023-08-14 13:09 UTC, vovasalyha commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            return affectedRows >= 1;
More correct to do like this.
```suggestion
            return affectedRows > 0;

```

2023-08-14 13:09 UTC, vovasalyha commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            if (affectedRows < ROW_EXIST_NUM) {
It's okay if zero rows are affected, do not throw an Exception.

2023-08-14 15:28 UTC, vovasalyha approved these changes

2023-08-14 15:28 UTC, vovasalyha commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            throw new RuntimeException("Can't create a connection to the DB" ,e);
Please use `DataProcessingException` everywhere. And pay attention to error messages. Connection problems is not the only reason why exception can be thrown, think about better message for this context.

2023-08-14 15:28 UTC, vovasalyha commented on src/main/resources/init_db.sql
> +    title VARCHAR(50) NOT NULL,
It's too restrictive length IMO. There are books with longer names for sure.

2023-08-14 15:28 UTC, vovasalyha commented on src/main/java/mate/academy/dao/BookDaoImpl.java
> +            List<Book> allBooks = new ArrayList<>();
```suggestion
            List<Book> books = new ArrayList<>();

```

2024-04-22 11:08 UTC, closed without merging